version: '3.3'
services:
  backend:
    image: pisit/234project-backend:latest
    ports:
      - "7071:8080"
  frontend:
    image: dto80/234project-frontend:latest
    ports:
      - "7072:80"
    volumes:
      - type: bind
        source: ./Project234
        target: /usr/share/nginx/html/assets

